### ISSUE TITLE
Runtime error index out of range[1] with length 0 when rerunning ./pimp-my-shell

### ISSUE THREAD

**Issue by TheZenTester** [mr-pmillz/pimp-my-shell#53]
**Describe the bug**
I had followed the instructions on how to install for mac (`git clone`, `go build` --> `./pimp-my-shell`) and thought it had installed without any errors.  However, in restarting my terminal, nothing loaded.  When I try to rerun `./pimp-my-shell` I get an error:

```
goroutine 1 [running]:
github.com/mr-pmillz/pimp-my-shell/zsh.updateZSHPlugins({0xc000032140, 0x1e})
        ~/Downloads/pimp-my-shell/zsh/zsh.go:29 +0x615
github.com/mr-pmillz/pimp-my-shell/zsh.InstallOhMyZsh({0x155b888, 0x6}, 0xc000212d60)
        ~/Downloads/pimp-my-shell/zsh/zsh.go:197 +0x7be
main.pimpMyShell({0x155b888, 0x6}, 0xc000212d60, 0x1?)
        ~Downloads/pimp-my-shell/main.go:73 +0x26a
main.main()
```

This occurs when attempting to run in a regular iterm2 terminal, but also attempted on a Mac standard install terminal 

**To Reproduce**
1. `git clone https://github.com/mr-pmillz/pimp-my-shell.git`
2. `cd pimp-my-shell`
3. `go build`
4. `./pimp-my-shell`
5. Let the install process occur. At this point there was no noticeable change to my terminal, even after restart.
6. Attempt to run `./pimp-my-shell` again
7. error message

**Screenshots**
![image](https://user-images.githubusercontent.com/96437320/208996290-40c06929-2436-4701-aabb-d572b7cf5460.png)

**Desktop (please complete the following information):**

 - Device: Macbook Pro 2018
 - OS: MacOS Monterey 12.6.2
 - iTerm2 Version: 3.4.18
 - Mac Terminal: 2.12.7

**Comment by mr-pmillz** [comment]
Hey @TheZenTester 
Thank you for bringing this to my attention,
I believe I have a fix for the issue, and will push a new release soon 💯

**Comment by mixedup4x4** [comment]
same issue on my Mac 
Device: Macbook Pro 2018
OS: MacOS Venture 13.1
iTerm2 Version: Build 3.4.18
Mac Terminal: Version 2.13 (447)

**Comment by mr-pmillz** [comment]
Fixed bug https://github.com/mr-pmillz/pimp-my-shell/commit/0b29199cf793b192b3d090014cd7673aa36c4690

Also, if you're running on Mac, ensure that you also have xcode build tools installed prior to running the pimp-my-shell binary as YCM vim plugin requires this. @mixedup4x4  @TheZenTester 
```shell
xcode-select --install
```

Also, I released v2.0.8 which will work with go install now 👍 
Let me know if the issue still persists or if it is resolved, and I can re-open the issue : )

**Comment by mixedup4x4** [comment]
panic: runtime error: index out of range [1] with length 0

I have Xcode build tools already installed and still get this error
